import asyncio
from typing import AsyncGenerator, Optional, List, Dict, Any
from openai import AsyncOpenAI, APIError, RateLimitError, APITimeoutError, APIConnectionError

from app.core.config import settings
from app.core.logging import logger


class LLMGeneratorEngine:
    """Async engine for OpenAI-compatible LLM inference (OpenRouter, Groq, OpenAI)."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        default_model: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
    ) -> None:
        self.api_key = api_key if api_key is not None else settings.LLM_API_KEY
        self.base_url = base_url or settings.LLM_BASE_URL
        self.default_model = default_model or settings.LLM_MODEL
        self.temperature = temperature if temperature is not None else settings.LLM_TEMPERATURE
        self.max_tokens = max_tokens if max_tokens is not None else settings.LLM_MAX_TOKENS
        self.timeout = timeout if timeout is not None else settings.LLM_TIMEOUT_SECONDS
        self.max_retries = max_retries if max_retries is not None else settings.LLM_MAX_RETRIES
        self.provider = settings.LLM_PROVIDER

        # Fallback placeholder key for offline/mock testing if key is empty
        effective_key = self.api_key if self.api_key else "placeholder_dev_key"

        init_kwargs: Dict[str, Any] = {
            "api_key": effective_key,
            "timeout": self.timeout,
        }
        if self.base_url:
            init_kwargs["base_url"] = self.base_url

        self.client = AsyncOpenAI(**init_kwargs)

    async def generate_answer(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        max_tokens: Optional[int] = None,
    ) -> str:
        """
        Generate grounded answer completion with retries and backoff.

        Args:
            messages: List of ChatCompletion message dictionaries [{"role": "system", ...}, ...].
            model: Optional model identifier override.
            max_tokens: Optional max output tokens override.

        Returns:
            String response content generated by LLM.
        """
        target_model = model or self.default_model
        tokens_limit = max_tokens or self.max_tokens

        logger.info(
            "Executing LLM generation request",
            provider=self.provider,
            model=target_model,
            base_url=self.base_url,
            message_count=len(messages),
        )

        attempt = 0
        last_exception = None

        while attempt <= self.max_retries:
            try:
                response = await self.client.chat.completions.create(
                    model=target_model,
                    messages=messages,  # type: ignore
                    temperature=self.temperature,
                    max_tokens=tokens_limit,
                )
                content = response.choices[0].message.content or ""
                logger.info(
                    "LLM generation completed successfully",
                    model=target_model,
                    content_length=len(content),
                )
                return content

            except (RateLimitError, APITimeoutError, APIConnectionError) as e:
                attempt += 1
                last_exception = e
                if attempt > self.max_retries:
                    logger.error("Max retries exceeded for LLM provider API", error=str(e), attempts=attempt)
                    raise RuntimeError(f"LLM Provider transient error: {str(e)}") from e

                backoff_seconds = 2.0 ** attempt
                logger.warning(
                    "Transient LLM provider failure, retrying...",
                    attempt=attempt,
                    backoff_seconds=backoff_seconds,
                    error=str(e),
                )
                await asyncio.sleep(backoff_seconds)

            except APIError as e:
                logger.error("LLM Provider API Error", status_code=getattr(e, "status_code", None), error=str(e))
                raise RuntimeError(f"LLM Provider API Error: {str(e)}") from e

        raise RuntimeError(f"LLM generation failed: {str(last_exception)}")

    async def generate_answer_stream(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        max_tokens: Optional[int] = None,
    ) -> AsyncGenerator[str, None]:
        """
        Yield completion tokens incrementally as an AsyncGenerator.
        Prepared for Phase 9 Server-Sent Events (SSE) streaming endpoint.
        """
        target_model = model or self.default_model
        tokens_limit = max_tokens or self.max_tokens

        logger.info(
            "Starting streaming LLM request",
            provider=self.provider,
            model=target_model,
        )

        response_stream = await self.client.chat.completions.create(
            model=target_model,
            messages=messages,  # type: ignore
            temperature=self.temperature,
            max_tokens=tokens_limit,
            stream=True,
        )

        async for chunk in response_stream:  # type: ignore
            if chunk.choices and chunk.choices[0].delta.content:
                yield chunk.choices[0].delta.content
